- hosts: all
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: 10.138.0.4
    ansible_user: admin
    ansible_httpapi_password: Nomios101
    ansible_httpapi_use_ssl: yes

  tasks:
    - name: Collect BIG-IP information
      bigip_device_info:
        gather_subset:
          - interfaces
          - vlans

    - name: Collect all BIG-IP information
      bigip_device_info:
        gather_subset:
          - all
