---

- name: Use Collections
  hosts: f5
  connection: local
  
  tasks:
    - f5networks.f5_modules.bigip_config:
        save: yes
        provider:
          server: lb.mydomain.com
          password: secret
          user: admin

        
   

    
