---



- name: Restore conf
  hosts: all
  gather_facts: False
  
  tasks:  

    - name: Reset the BIG-IP configuration, for example, to RMA the device
      shell: tmsh load /sys config no-passphrase azzedeen
        
   

    
