---

- name: Use Collections
  hosts: f5
  connection: local
  
  tasks:
    - f5networks.f5_modules.bigip_config:
        save: yes
        provider:
          server: 10.138.0.2
          password: Nomios101 
          user: admin

        
   

    
