---

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local
  
  vars:
    provider:
      password: Nomios101
      server: 10.138.0.2
      user: admin
      validate_certs: no
      server_port: 8443
    
  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
        
    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      with_items:
        - host: 10.10.10.10
          name: web01
        - host: 10.10.10.20
          name: web02

    
    
  
