---

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local
  
  vars:
    provider:
      password: Nomios101
      server: 10.138.0.2
      user: admin
      validate_certs: no
      server_port: 8443
    

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
    
    
  
